version: '{build}'
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  project: DiscordBee.sln
  verbosity: minimal
after_build:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false") {
      Start-Process -FilePath "7z" -ArgumentList "a", "$env:APPVEYOR_PROJECT_NAME-$env:CONFIGURATION-$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER.zip", "$env:APPVEYOR_BUILD_FOLDER\bin\$env:CONFIGURATION\*", "-xr!*.pdb"
    } else {
      Start-Process -FilePath "7z" -ArgumentList "a", "$env:APPVEYOR_PROJECT_NAME-$env:CONFIGURATION-$env:APPVEYOR_REPO_TAG_NAME.zip", "$env:APPVEYOR_BUILD_FOLDER\bin\$env:CONFIGURATION\*", "-xr!*.pdb"
    }
artifacts:
- path: bin/$(configuration)/**/*
  name: Plugin
- path: '*$(configuration)-*.zip'
  name: Plugin-Package
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: SJlJq7xJ+SMLC43wkfzf15YFHmZZ+G5ZI9op1LYgjZCahxXHut1ai4yV2pP0zsXs
  artifact: Plugin-Package
  draft: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true