version: '{build}'
image: Visual Studio 2022
configuration: Release
before_build:
- ps: nuget restore
build:
  project: DiscordBee.sln
  verbosity: minimal
after_build:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "false") {
      Start-Process -FilePath "7z" -ArgumentList "a", "$env:APPVEYOR_PROJECT_NAME-$env:CONFIGURATION-$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER.zip", "$env:APPVEYOR_BUILD_FOLDER\bin\$env:CONFIGURATION\*"
    } else {
      Start-Process -FilePath "7z" -ArgumentList "a", "$env:APPVEYOR_PROJECT_NAME-$env:CONFIGURATION-$env:APPVEYOR_REPO_TAG_NAME.zip", "$env:APPVEYOR_BUILD_FOLDER\bin\$env:CONFIGURATION\*"
    }
artifacts:
- path: bin/$(configuration)/**/*
  name: Plugin
- path: '*$(configuration)-*.zip'
  name: Plugin-Package
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: bDkjepIUlFRHs/1W8BpNMCgEBqtOkbp6BOlZgUEs2h1iA/n1TVbdnRKuBburxAQY
  artifact: Plugin-Package
  draft: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
